#!/usr/bin/env bash

tint2 &
bash ~/scripts/fdpowermon_run.sh &
nm-applet &

# Wait a little bit for nm-applet to be started, to get order the icons in the system tray of tint2
sleep 1

# Volume icon
pasystray --notify=sink_default --notify=source_default &
