#!/usr/bin/env bash

# This caja script open and follow a file in a terminal with the command
# `tail -n +1 -f`

INPUT_FILE=$(readlink -f "${1}")
INPUT_DIRNAME=$(dirname "${INPUT_FILE}")
INPUT_FILENAME=$(basename "${INPUT_FILE}")

if [[ ! -e "${INPUT_FILE}" ]]; then
	zenity --no-wrap --error --text="Cannot find ${INPUT_FILE}"
	exit 1
fi

if [[ ! -f "${INPUT_FILE}" ]]; then
	zenity --no-wrap --error --text="Cannot use this script on a directory"
	exit 1
fi

COMMAND=$(printf "cd '%s';tail -f '%s'" "${INPUT_DIRNAME}" "${INPUT_FILENAME}")
x-terminal-emulator -e "bash -c \"${COMMAND}\""
