#!/usr/bin/env bash

# This caja script shows a zenity file/directory selector and start
# a comparison with meld

DIFF_SOURCE_LEFT=$(readlink -f "${1}")
DIFF_SOURCE_RIGHT=""

if [ -d "${DIFF_SOURCE_LEFT}" ]; then
	DIFF_SOURCE_RIGHT=$(zenity --file-selection --directory --title="Choose the file or directory to diff with (meld)")
else
	DIFF_SOURCE_RIGHT=$(zenity --file-selection --title="Choose the file or directory to diff with (meld)")
fi
if [ "$?" -eq 1 ]; then
	exit 1
fi
DIFF_SOURCE_RIGHT=$(awk -F, '{print $1}' <<<${DIFF_SOURCE_RIGHT})
DIFF_SOURCE_RIGHT=$(readlink -f "${DIFF_SOURCE_RIGHT}")
if [ ! -e "${DIFF_SOURCE_LEFT}" ]; then
	zenity --no-wrap --error --text="Can not find ${DIFF_SOURCE_LEFT}"
	exit 1
fi
if [ ! -e "${DIFF_SOURCE_RIGHT}" ]; then
	zenity --no-wrap --error --text="Can not find ${DIFF_SOURCE_RIGHT}"
	exit 1
fi
meld "${DIFF_SOURCE_LEFT}" "${DIFF_SOURCE_RIGHT}"
