#!/usr/bin/env bash

function indent_json_as_copy(){
	FILE=$(readlink -f "${1}")
	
	if [[ ! -e "${FILE}" ]]; then
		zenity --no-wrap --error --text="Cannot find ${FILE}"
		return
	fi
	
	if [[ ! -f "${FILE}" ]]; then
		zenity --no-wrap --error --text="'$(basename "${BASH_SOURCE}")' works on files only"
		return
	fi
	
	FILE_TO_INDENT="${FILE}.$(date '+%y%m%d-%H%M%S').indented.json"
	
	cat "${FILE}" | jq . >"${FILE_TO_INDENT}.tmp" 2>"${FILE_TO_INDENT}.log"
	RETURN_CODE=$?
	
	if [[ "${RETURN_CODE}" -eq 0 ]]; then
		mv "${FILE_TO_INDENT}.tmp" "${FILE_TO_INDENT}"
		if [[ -e "${FILE_TO_INDENT}.log" ]]; then
			rm -f "${FILE_TO_INDENT}.log"
		fi
	else
		zenity --no-wrap --error --text="An error occurred while indenting ${FILE}"
		if [[ -e "${FILE_TO_INDENT}.tmp" ]]; then
			rm -f "${FILE_TO_INDENT}.tmp"
		fi
	fi
}

coproc ( for FILE in "${@}"; do indent_json_as_copy "${FILE}"; done )
